disable = ["gnome_shell_extensions"]


[brew]
greedy_cask = false

[commands]
"helm repos" = "helm repo update"
"helm plugins" = "helm plugin list | sed 's/\\s.*$//' | tail -n +2 | xargs -n 1 helm plugin update"